#!/usr/bin/env bash

alias ls='ls --color=auto --group-directories-first'
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias lt='ls -lhtr'
alias lsd='ls -d */'
alias lsf='ls -p | grep -v /'
alias lh='ls -lh'
alias lS='ls -lhS'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rg='grep -r'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ~='cd ~'
alias -- -='cd -'
alias cd..='cd ..'

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -Iv'
alias mkdir='mkdir -pv'
alias rmdir='rmdir -v'

alias df='df -h'
alias du='du -h'
alias dus='du -sh'
alias dud='du -d 1 -h'
alias free='free -h'
alias ps='ps auxf'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
alias jobs='jobs -l'

alias ping='ping -c 5'
alias ports='netstat -tulanp'
alias listening='lsof -i -P | grep LISTEN'
alias myip='curl -s ifconfig.me'
alias localip="ip addr show | grep 'inet ' | grep -v 127.0.0.1 | awk '{print \$2}' | cut -d/ -f1"

alias c='clear'
alias h='history'
alias j='jobs -l'
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias nowtime='date +"%T"'
alias nowdate='date +"%Y-%m-%d"'
alias week='date +%V'

alias g='git'
alias gs='git status -sb'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit -v'
alias gcm='git commit -m'
alias gcs='git commit -S -m'
alias gca='git commit --amend'
alias gp='git push'
alias gpl='git pull'
alias gf='git fetch'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gm='git merge'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log --oneline --graph --decorate --all -20'
alias gll='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias gst='git stash'
alias gsta='git stash apply'
alias gstp='git stash pop'
alias gstl='git stash list'
alias gclone='git clone'
alias gr='git remote'
alias grv='git remote -v'

alias d='docker'
alias dc='docker-compose'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias dex='docker exec -it'
alias dlogs='docker logs -f'
alias dprune='docker system prune -af'
alias dstop='docker stop $(docker ps -q)'

alias t='tmux'
alias ta='tmux attach -t'
alias tl='tmux list-sessions'
alias tn='tmux new -s'
alias tk='tmux kill-session -t'

alias v='vim'
alias vi='vim'
alias svi='sudo vim'

alias bashrc='$EDITOR ~/.bashrc'
alias vimrc='$EDITOR ~/.vimrc'
alias i3config='$EDITOR ~/.config/i3/config'
alias reload='source ~/.bashrc'
alias reload-i3='i3-msg reload'
alias restart-i3='i3-msg restart'

alias meminfo='free -h'
alias cpuinfo='lscpu'
alias diskinfo='df -h'
alias biggest='du -sh * | sort -rh | head -10'
alias temp='sensors'

alias dt='date "+%Y%m%d%H%M%S"'
alias timestamp='date +%s'

alias weather='curl wttr.in'
alias moon='curl wttr.in/Moon'